### ISSUE TITLE
Back button does not automatically appear

### ISSUE THREAD

**Issue by hackily** [PredixDev/px-navbar#1]
Hey there! May I ask what environment you are developing on?

I'm running a local nodejs server and browsing to my pages with chrome 51. I'm having difficulty getting the back button to automatically display.

My understanding is that as long as I have the "main" tag in my main page, all the other pages should automatically have the back button show up.
See my code below:

```
<px-pages id="pages" debug>
    <px-page id="page1" main title="Main Page">
        <px-navbar id="navbar1">
            <div right>
                <button class="navbar__button fa fa-plus"></button>
            </div>
        </px-navbar>
    </px-page>
    <px-page id="page2" title="Page 2">
        <px-navbar></px-navbar>
    </px-page>
    <px-page id="page3" title="Page 3">
        <px-navbar></px-navbar>
    </px-page>
</px-pages>
```

Thanks!

**Comment by jonniespratley** [comment]
Hi, thanks for your submission. Yes there was a change in the API since we don't want these components to know about one another. I've update the component and will send out a working jsbin demo.

**Comment by jonniespratley** [comment]
Here is a jsbin. http://jsbin.com/sesedo/edit?html,output
